#! /bin/bash

#case  $# in
#	1)n=1 ; while [ $n -ne $1 ] ; do ; echo $n ; n=$(($n+1)) ; done ;;
#	2)n=$1 ; while [ $1 -ne $2 ] ; do ; echo $n ; n=$(($n+1)) ; done ;;
#	3)n=$1 ; while [ $1 -ne $2 ] ; do ; echo $n ; n=$(($n+$3)) ; done ;;
#esac

# correction

m=1
k=1
case $# in
	1)n=$1;;
	2)m=$1; n=$2;;
	3)m=$1; k=$2; n=$3;;
	*)echo "erreur"; exit ;;
esac


i=$m
while [ $i -le $n ] ;do
	echo $i
	i=$((i+k))
done 
