insert into Personne (numPers, nomPers, prenomPers, sexePers) values(1, 'Dubois','Anne','F');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(2, 'Durand','Alain','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(3, 'Dupont','Eric','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(4, 'Dunois','Marie','F');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(5, 'Durand','Pierre','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(6, 'Dupont','Daniel','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(7, 'Berthier','Aline','F');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(8, 'Durand','Paul','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(9, 'Durand','Odile','F');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(10, 'Dupont','Jeanne','F');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(11, 'Dupont','Nicolas','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(12, 'Dupont','Maxime','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(13, 'Durand','Luc','M');
insert into Personne (numPers, nomPers, prenomPers, sexePers) values(14, 'Durand','Monique','F');

insert into PereDe (numPersEnfant, numPersPere) values(5, 2);
insert into PereDe (numPersEnfant, numPersPere) values(8, 5);
insert into PereDe (numPersEnfant, numPersPere) values(9, 5);
insert into PereDe (numPersEnfant, numPersPere) values(13, 8);
insert into PereDe (numPersEnfant, numPersPere) values(6, 3);
insert into PereDe (numPersEnfant, numPersPere) values(10, 6);
insert into PereDe (numPersEnfant, numPersPere) values(11, 6);
insert into PereDe (numPersEnfant, numPersPere) values(12, 6);

insert into MereDe (numPersEnfant, numPersMere) values(5, 1);
insert into MereDe (numPersEnfant, numPersMere) values(8, 4);
insert into MereDe (numPersEnfant, numPersMere) values(9, 4);
insert into MereDe (numPersEnfant, numPersMere) values(10, 4);
insert into MereDe (numPersEnfant, numPersMere) values(11, 4);
insert into MereDe (numPersEnfant, numPersMere) values(12, 4);
insert into MereDe (numPersEnfant, numPersMere) values(13, 7);
insert into MereDe (numPersEnfant, numPersMere) values(14, 9);
